### ISSUE TITLE
compatibility with Eigen 3.4

### ISSUE THREAD

**Issue by vzantedeschi** [deep-spin/lp-sparsemap#9]
[Eigen](https://eigen.tuxfamily.org/index.php?title=Main_Page)'s default version is in C++14, hence installing LP-SparseMAP with it raises compiler errors.

Suggested change:  line 16 of 'setup.py' to  '-std=c++14',

**Comment by vene** [comment]
did it compile for you with no errors after this? If yes sounds good, let’s see what CI has to say.

**Comment by vzantedeschi** [comment]
Yes, it compiles with that change
